[package]
name = "pbr-chain"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10.8"


actix-web = "4"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
